config/routes.rb
Rails.application.routes.draw do
  resources :employers do
    member do
      get 'authenticate_email'
    end
    collection do
      get  'conform_phone_number'
      post 'authenticate_phone_number'
    end
  end

  resources :employer_sessions, only: [] do
    collection do
      post 'sign_in'
      get  'sign_out'
      get  'home'
    end
  end

  root 'employer_sessions#home'

end

app/models/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_save :generate_verifications_tokens
    after_save :sent_verifications
  end

  def generate_verifications_tokens
    generate_email_token if email.present? && email_changed?
    generate_phone_token if phone_number.present? && phone_number_changed?
  end

  def generate_email_token
    begin
    self.email_token = SecureRandom.urlsafe_base64.to_s
    self.is_email_verified = false
  end while self.class.exists?(email_token: email_token)
  end

  def generate_phone_token
    begin
       self.phone_token = SecureRandom.hex(3)
       self.is_phone_verified = false
     end while self.class.exists?(phone_token: phone_token)
  end

  def sent_verifications
    sent_email_verification if email.present? && email_changed?
    sent_phone_number_verifications if phone_number.present? && phone_number_changed?
  end

  def from
    ENV['FROM']
  end

  def to
    # with country code
    phone_number
  end

  def body
    "Please Use this code '#{phone_token}' to
     verify your phone number"
  end

  def sent_phone_number_verifications
    @twilio = Twilio::REST::Client.new(ENV['TWILO_SID'], ENV['TWILIO_SECRET_KEY'])

    begin
     @twilio.account.messages.create(from: from,
                                     to: to,
                                     body: body)
   rescue Twilio::REST::RequestError => e
     puts e
   end
  end

  def sent_verifications
    EmployerMailer.conform_registration(self).deliver_now
  rescue Net::SMTPAuthenticationError, Net::SMTPUnknownError => e
  end
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  include Authentication
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true,
                           numericality: true,
                           length: { minimum: 10, maximum: 15 }
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  # validates :phone_number, uniqueness:{ scope :email, message: "Already registered with this email" }

  def mark_email_as_verified
    update!(is_email_verified: true)
  end

  def mark_phone_number_as_verified
    update!(is_phone_verified: true)
  end

  def is_authenticated_user?
    is_email_verified && is_phone_verified
  end
end

app/models/employer_session.rb
class EmployerSesssion < ActiveType::Object
  attribute :email, :string
  attribute :phone_number, :string
  validates :email, presence: true

  def self.employer(email)
    Employer.sign_in(email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :login_required!, only: [:show, :index]

  private

  def login_required!
    redirect_to root_path unless current_user
  end

  def current_user
    @currnt_employer ||= Employer.find session[:employer_id] if session[:employer_id].present?
  end
end

app/controllers/employer_sessions_controller.rb
class EmployerSessionsController < ApplicationController
  def sign_in
    find_employer
    if @employer.present?
      if @employer.is_authenticated_user?
        session[:employer_id] = @employer.id
        flash[:sucess] = 'Login Succesful'
        redirect_to @employer
      else
        flash[:error] = 'You are not verified Email and Phone Number'
        redirect_to root_path
      end
    else
      flash[:error] = 'Invalid Email'
      redirect_to root_path
     end
  end

  def sign_out
    @current_employer = session[:employer_id] = nil
    redirect_to root_path
  end

  private

  def find_employer
    puts params[:email]
    @employer ||= Employer.find_by_email(params[:email])
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :load_employer, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
  end

  def new
    build_employer
  end

  def edit
  end

  def create
    build_employer
    if @employer.save
      flash[:sucess] = 'Employer created'
      redirect_to conform_phone_number_employers_path
    else
      render :new
    end
  end

  def authenticate_email
    @employer = Employer.find_by_email_token(params[:id])
    if @employer
      if @employer.is_email_verified
        flash[:info] = 'Your Email already validated'
      else
        @employer.mark_email_as_verified
        flash[:sucess] = 'Your Email sucessfullly validated'
      end
      # session[:employer_id] = @employer.id
    else
      flash[:error] = 'Invalid Authentication'
     end
    redirect_to root_path
  end

  def authenticate_phone_number
    @employer = Employer.find_by_phone_token(params[:code])
    if @employer
      if @employer.is_phone_verified
        flash[:info] = 'Your Phone Number already validated'
      else
        @employer.mark_phone_number_as_verified
        flash[:sucess] = 'Your Phone sucessfullly validated'
      end
      # session[:employer_id] = @employer.id
    else
      flash[:error] = 'Invalid Authentication'
    end
    redirect_to root_path
  end

  def conform_phone_number
  end

  def home
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private

  def load_employers
    @employers ||= employers_scoped.to_a
  end

  # Use callbacks to share common setup or constraints between actions.
  def load_employer
    @employer = Employer.find(params[:id])
  end

  def build_employer
    @employer ||= Employer.new(employer_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employer_params
    employer_params = params[:employer]
    employer_params.present? ? employer_params.permit(:name, :email, :dob, :location, :phone_number) : {}
  end

  def employer_scoped
    Employer.scoped
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :success then 'alert-success'
    when :error then 'alert-danger'
    when :notice then 'alert-info'
    else 'alert-danger'
    end
  end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<div style="width:70%"> 
<%= form_for @employer,:html=>{:class=>'form-horizontal'} do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name,:class=>"form-control input-md" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email,:class=>"form-control input-md" %>
  </div>
  <div class="form-group">
    <%= f.label :dob %>
    <%= f.date_select :dob,start_year: 1980 %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location,:class=>"form-control input-md" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number,:class=>"form-control input-md" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit",:class=>'btn btn-primary'%>
  </div>
<% end %>

app/views/employers/conform_phone_number.html.erb
<%=form_for "employee",:url => authenticate_phone_number_employers_path do  |f|%>
	<%=text_field_tag "code" %>
	<%=f.submit "Verify your Phone Number" %>
<%end%>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/home.html.erb
<%=form_for "email",:url=>{:action=>"sign_in"} do |f|%>
	<div class="form-group">
	    <%= label_tag "Email" %>  : 
	   <%=text_field_tag "email" ,'',:placeholder=>"Enter your email"%>
	</div>
	 <%= submit_tag "Login", class: "btn btn-primary btn-lg" %>
<%end%>
<%=link_to "Registration",new_employer_path%>
<%= link_to ' Msg verification', conform_phone_number_employers_path %>

app/views/employers/index.html.erb
<div>
<p id="notice"><%= notice %></p>

<h1>Listing Employers</h1>

<table  class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Location</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.name %></td>
        <td><%= employer.email %></td>
        <td><%= employer.dob.to_date %></td>
        <td><%= employer.location %></td>
        <td><%= employer.phone_number%></td>
        <td><%= link_to 'Show', employer %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/employers/show.html.erb
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
           <A href="edit.html" > <%= link_to 'Edit', edit_employer_path(@employer) %> </a></A>

        <A href="edit.html" ><%=link_to "Sign out",sign_out_employer_sessions_path%></A>
       <br>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @employer.name %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>date of Birth:</td>
                        <td><%= @employer.dob.to_date%></td>
                      </tr>
                      <tr>
                        <td>Location </td>
                        <td><%= @employer.location%></td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><%= @employer.email %></td>
                      </tr>
                        <td>Phone Number</td>
                        <td>
                        <%= @employer.phone_number %>
                        </td>
                           
                      </tr>
                     
                    </tbody>
                  </table>
              
                </div>
              </div>
            </div>            
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployerRegistration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="navbar navbar-inverse navbar-static-top">
        <ul class="nav navbar-nav navbar-right">
      </div>
    </div>
 </div>
 <div class="container">
    <% flash.each do |key, value| %>
	        <div class="alert <%= flash_class(key) %> " role="alert"><%= value %></div>
	 <% end %>
<%= yield %>
</div>
</body>
</html>